homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

# USUARIOS

users_page:
    path:     /users
    defaults: { _controller: AppBundle:Users:index }

# ADMIN

admin_page: 
    path:     /admin
    defaults: { _controller: AppBundle:Admin:index }

# LOGIN

login:
    path:     /login
    defaults: { _controller: AppBundle:Login:login }

logout:
    path:     /logout

registration:
    path:     /register
    defaults: { _controller: AppBundle:Login:register }
